#[cfg(any(feature = "google-cloud-videointelligence-v1"))]
pub mod v1;
#[cfg(any(feature = "google-cloud-videointelligence-v1beta2"))]
pub mod v1beta2;
#[cfg(any(feature = "google-cloud-videointelligence-v1p1beta1"))]
pub mod v1p1beta1;
#[cfg(any(feature = "google-cloud-videointelligence-v1p2beta1"))]
pub mod v1p2beta1;
#[cfg(any(feature = "google-cloud-videointelligence-v1p3beta1"))]
pub mod v1p3beta1;
