#[cfg(any(feature = "google-cloud-vision-v1"))]
pub mod v1;
#[cfg(any(feature = "google-cloud-vision-v1p1beta1"))]
pub mod v1p1beta1;
#[cfg(any(feature = "google-cloud-vision-v1p2beta1"))]
pub mod v1p2beta1;
#[cfg(any(feature = "google-cloud-vision-v1p3beta1"))]
pub mod v1p3beta1;
#[cfg(any(feature = "google-cloud-vision-v1p4beta1"))]
pub mod v1p4beta1;
