#[cfg(any(feature = "google-ads-googleads-v10-common"))]
pub mod common;
#[cfg(any(feature = "google-ads-googleads-v10-enums"))]
pub mod enums;
#[cfg(any(feature = "google-ads-googleads-v10-errors"))]
pub mod errors;
#[cfg(any(feature = "google-ads-googleads-v10-resources"))]
pub mod resources;
#[cfg(any(feature = "google-ads-googleads-v10-services"))]
pub mod services;
